### ISSUE TITLE
Entity creation not working on 1.20.2 with magic version 1.8.12

### ISSUE THREAD

**Issue by LadyHaley** [elBukkit/MagicPlugin#1321]
https://cdn.discordapp.com/attachments/511088611769188353/1211897474055405588/latest.log
The log is about 10mb too big for github to upload

The error I can see with my layman eyes is the following being repeated

`[04:44:33 WARN]: java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.craftbukkit.v1_20_R2.CraftWorld.createEntity(org.bukkit.Location, java.lang.Class)'
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.utility.platform.v1_20_2.CompatibilityUtils.createEntity(CompatibilityUtils.java:317)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.entity.EntityData.trySpawn(EntityData.java:694)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.entity.EntityData.spawn(EntityData.java:769)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.builtin.SpawnEntityAction.spawn(SpawnEntityAction.java:218)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.builtin.SpawnEntityAction.step(SpawnEntityAction.java:143)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:121)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:43)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:221)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:109)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:43)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:221)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.batch.ActionBatch.process(ActionBatch.java:38)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.magic.Mage.processPendingBatches(Mage.java:2008)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.magic.MagicController.processPendingBatches(MagicController.java:1633)
[04:44:33 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.tasks.BatchUpdateTask.run(BatchUpdateTask.java:14)
[04:44:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[04:44:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[04:44:33 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1470)
[04:44:33 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[04:44:33 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1379)
[04:44:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[04:44:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:44:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by LadyHaley** [comment]
Using Cornelias Clairvoyance spell, I get this error which is a one off and doesnt repeat while the spell is active

`[04:49:23 WARN]: java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.craftbukkit.v1_20_R2.CraftWorld.createEntity(org.bukkit.Location, java.lang.Class)'
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.utility.platform.v1_20_2.CompatibilityUtils.createEntity(CompatibilityUtils.java:317)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.entity.EntityData.trySpawn(EntityData.java:694)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.entity.EntityData.spawn(EntityData.java:769)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.builtin.SpawnEntityAction.spawn(SpawnEntityAction.java:218)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.builtin.SpawnEntityAction.step(SpawnEntityAction.java:143)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:102)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:43)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:221)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:109)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:43)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:221)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.action.ActionHandler.cast(ActionHandler.java:158)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.spell.ActionSpell.startCast(ActionSpell.java:172)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:154)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1769)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1566)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1447)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1431)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.magic.command.CastCommandExecutor.processCastCommand(CastCommandExecutor.java:181)
[04:49:23 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.magic.command.CastCommandExecutor.onCommand(CastCommandExecutor.java:149)
[04:49:23 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[04:49:23 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[04:49:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991)
[04:49:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[04:49:23 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[04:49:23 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[04:49:23 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[04:49:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2208)
[04:49:23 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2168)
[04:49:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[04:49:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[04:49:23 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:49:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[04:49:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[04:49:23 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[04:49:23 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[04:49:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[04:49:23 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[04:49:23 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[04:49:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[04:49:23 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[04:49:23 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[04:49:23 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:49:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by LadyHaley** [comment]
Here is the link to Corns spell in the magic discord
https://discord.com/channels/580099743875727363/580101165098729478/1199402851466752081

**Comment by LadyHaley** [comment]
Version info for my related plugins and server

`[27/02/2024 15:51:55 pm] [Render thread/INFO] [System] [CHAT] Checking version, please wait...
[27/02/2024 15:51:55 pm] [Render thread/INFO] [System] [CHAT] This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)\nYou are running the latest version\nPrevious version: git-Paper-196 (MC: 1.20.1)
[27/02/2024 15:52:00 pm] [Render thread/INFO] [System] [CHAT] Magic 10.8.12-82f9295
[27/02/2024 15:52:00 pm] [Render thread/INFO] [System] [CHAT] Use /mhelp for help
[27/02/2024 15:52:00 pm] [Render thread/INFO] [System] [CHAT] Search help topics with /mhelp broom not working
[27/02/2024 15:52:05 pm] [Render thread/INFO] [System] [CHAT] Insufficient arguments. You need at least 1
[27/02/2024 15:52:05 pm] [Render thread/INFO] [System] [CHAT] /protocol config|check|update|timings|listeners|version|dump
[27/02/2024 15:52:11 pm] [Render thread/INFO] [System] [CHAT] ProtocolLib v5.2.0-SNAPSHOT-679
[27/02/2024 15:52:11 pm] [Render thread/INFO] [System] [CHAT] Authors: dmulloy2 and Comphenix
[27/02/2024 15:52:11 pm] [Render thread/INFO] [System] [CHAT] Issues: https://github.com/dmulloy2/ProtocolLib/issues
[27/02/2024 15:52:20 pm] [Render thread/INFO] [System] [CHAT] This server is running Lib's Disguises v10.0.42 by libraryaddict, formerly maintained by Byteflux and NavidK0.
[27/02/2024 15:52:20 pm] [Render thread/INFO] [System] [CHAT] Use /libsdisguises reload to reload the config. All disguises will be blown by doing this.
[27/02/2024 15:52:20 pm] [Render thread/INFO] [System] [CHAT] Use /libsdisguises help to see more help
[27/02/2024 15:52:21 pm] [Render thread/INFO] [System] [CHAT] This server supports the plugin developer!`

**Comment by LadyHaley** [comment]
I seem to be getting a similar error when summoning a mob from my magic config 
'[05:29:07 INFO]: LadyHaley issued server command: /mmob summon fire_elemental
[05:29:07 WARN]: java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.craftbukkit.v1_20_R2.CraftWorld.createEntity(org.bukkit.Location, java.lang.Class)'
[05:29:07 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.utility.platform.v1_20_2.CompatibilityUtils.createEntity(CompatibilityUtils.java:317)
[05:29:07 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.entity.EntityData.trySpawn(EntityData.java:694)
[05:29:07 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.entity.EntityData.spawn(EntityData.java:769)
[05:29:07 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.entity.EntityData.spawn(EntityData.java:740)
[05:29:07 WARN]:        at Magic-10.8.12.jar//com.elmakers.mine.bukkit.magic.command.MagicMobCommandExecutor.onCommand(MagicMobCommandExecutor.java:213)
[05:29:07 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[05:29:07 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[05:29:07 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991)
[05:29:07 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[05:29:07 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[05:29:07 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[05:29:07 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[05:29:07 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2208)
[05:29:07 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2168)
[05:29:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[05:29:07 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[05:29:07 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[05:29:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[05:29:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[05:29:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[05:29:07 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[05:29:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[05:29:07 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[05:29:07 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[05:29:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[05:29:07 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[05:29:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[05:29:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[05:29:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)'

**Comment by LadyHaley** [comment]
Repeated with this plugin list
![image](https://github.com/elBukkit/MagicPlugin/assets/3754909/d6710806-bf14-4432-83b7-f481184916f8)

**Comment by LadyHaley** [comment]
still happens with only these plugins on 1.20.2 paper build #318
![image](https://github.com/elBukkit/MagicPlugin/assets/3754909/83a17d1b-afe1-4b80-83c4-c47c43aab343)
Same config worked fine on 1.20.4 with same plugin versions
downgrading my magic version one version has resolved the issue on 1.20.2

**Comment by NathanWolf** [comment]
Can you please try this dev build here?

https://jenkins.elmakers.com/job/MagicPlugin/4271/artifact/Magic/target/Magic-10.9-SNAPSHOT.jar

This looks like an incompatibility issue with something the Spigot team did in the middle of 1.20.x, I think the dev builds have a good fix for it in place. Please let me know either way :)

**Comment by LadyHaley** [comment]
The issue still persists with this version

**Comment by NathanWolf** [comment]
Oops, I see now I only applied the fix for 1.20.4, please try this one when you can:

https://jenkins.elmakers.com/job/MagicPlugin/4274/artifact/Magic/target/Magic-10.9-SNAPSHOT.jar

That should have the same fix, but for 1.20.2

**Comment by LadyHaley** [comment]
The issue still persists with this version
also the snapshot builds are replacing RP icons with Skull icons

**Comment by NathanWolf** [comment]
Hm, strange- maybe this something different. Can you please pastebin the error again with the current dev build? The line numbers should be different, at least, it may help me narrow this down.

The spell icons have all changed to skulls, the RP has been changed to match. You can undo this if you need to (like if you're using a custom RP and don't want to update it). See the changelog for more info on that:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/CHANGELOG.md#109

**Comment by LadyHaley** [comment]
`[01:26:44] [Server thread/INFO]: LadyHaley issued server command: /mcast clairvoyance
[01:26:44] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.World.createEntity(org.bukkit.Location, java.lang.Class)'
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.utility.platform.v1_20_2.CompatibilityUtils.createEntity(CompatibilityUtils.java:316)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.entity.EntityData.trySpawn(EntityData.java:694)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.entity.EntityData.spawn(EntityData.java:769)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.builtin.SpawnEntityAction.spawn(SpawnEntityAction.java:218)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.builtin.SpawnEntityAction.step(SpawnEntityAction.java:143)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:102)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:43)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:221)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:109)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:43)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:221)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.action.ActionHandler.cast(ActionHandler.java:158)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.spell.ActionSpell.startCast(ActionSpell.java:172)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:154)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1771)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1567)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1448)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1432)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.magic.command.CastCommandExecutor.processCastCommand(CastCommandExecutor.java:181)
[01:26:44] [Server thread/WARN]: 	at Magic-10.9-SNAPSHOT.jar//com.elmakers.mine.bukkit.magic.command.CastCommandExecutor.onCommand(CastCommandExecutor.java:149)
[01:26:44] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:26:44] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[01:26:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991)
[01:26:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[01:26:44] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2208)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2168)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[01:26:44] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1371)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[01:26:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[01:26:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by NathanWolf** [comment]
Ok, thank you for your patience- this problem is really ugly, I've never seen differences between Paper and Spigot like this, or differences between minor versions, they really made a mess with this change :(

That said, I'm hoping this build has a real fix now:

https://jenkins.elmakers.com/job/MagicPlugin/4275/artifact/Magic/target/Magic-10.9-SNAPSHOT.jar

**Comment by LadyHaley** [comment]
That looks to have done the trick, thank you!!!
